### ISSUE TITLE
Failed to add package

### ISSUE THREAD

**Issue by ibanez4510** [porterjamesj/Gumbo.jl#12]
I get the following error when adding Gumbo via Pkg.add("Gumbo") on a recent (today) installation of Julia from git

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
===============================================[ ERROR: Gumbo ]===============================================

LoadError: failed process: Process(`tar xzf /home/ibanez/.julia/v0.4/Gumbo/deps/downloads/gumbo-1.0.tar.gz --directory=/home/ibanez/.julia/v0.4/Gumbo/deps/src`, ProcessExited(2)) [2]
while loading /home/ibanez/.julia/v0.4/Gumbo/deps/build.jl, in expression starting on line 19

==============================================================================================================

===============================================[ BUILD ERRORS ]===============================================

WARNING: Gumbo had build errors.

 - packages with build errors remain installed in /home/ibanez/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Gumbo")`
 - build a single package by running its `deps/build.jl` script

=============================================================================================================

**Comment by porterjamesj** [comment]
Gumbo doesn't support Julia 0.4 since I don't have the bandwidth to keep up with all the breaking changes, so for now you'll have to use 0.3 if you want to use Gumbo. I'm planning on updating to support 0.4 once a release candidate is cut.
