### ISSUE TITLE
URL dead?

### ISSUE THREAD

**Issue by jiahao** [porterjamesj/Gumbo.jl#13]
Dependency points to `http://jamesporter.me/julia/gumbo-1.0.tar.gz` but this URL now returns a 404

**Comment by porterjamesj** [comment]
uh oh, thanks for the report, I'll take a look. This is odd because I haven't unpdated my website in ages . . .

**Comment by porterjamesj** [comment]
hmmm that URL still works for me:

```
[james@xanthos 12:04 AM scratch] wget http://jamesporter.me/julia/gumbo-1.0.tar.gz
--2015-04-09 00:04:37--  http://jamesporter.me/julia/gumbo-1.0.tar.gz
Resolving jamesporter.me... 192.30.252.153, 192.30.252.154
Connecting to jamesporter.me|192.30.252.153|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 443095 (433K) [application/octet-stream]
Saving to: ‘gumbo-1.0.tar.gz’

100%[===================================================================================================================>] 443,095      871KB/s   in 0.5s

2015-04-09 00:04:38 (871 KB/s) - ‘gumbo-1.0.tar.gz’ saved [443095/443095]
```

and PkgEval is stlll passing: http://pkg.julialang.org/?pkg=Gumbo&ver=release

**Comment by jiahao** [comment]
Apparently I downloaded a tar file which was just a 404 page and that confused BinDeps. Just tried again and it seems to work now. Sorry for the noise.

**Comment by porterjamesj** [comment]
yeah, there was a time when it was 404ing when I reorganized my website, which caused a lot of pain since BinDeps cached the 404 page believing it to be the downloaded tarball and you had to go clear it out manually.
