### ISSUE TITLE
How  works with https ?

### ISSUE THREAD

**Issue by paulanalyst** [porterjamesj/Gumbo.jl#15]
_
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3600 (2015-02-25 15:26 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit f96c23c* (43 days old master)
|__/                   |  x86_64-w64-mingw32

julia> url="https://www.youtube.com/channel/UCdZwMpK-iWqCos46xPscDeg"
"https://www.youtube.com/channel/UCdZwMpK-iWqCos46xPscDeg"

julia>

julia> using HTTPClient.HTTPC

julia> using URIParser

julia> using Gumbo

julia> function customize_curl(curl)
             cc = LibCURL.curl_easy_setopt(curl, LibCURL.CURLOPT_USERAGENT, "Mozilla/5.0 (Windows NT 6.1; rv:28.0)
 Gecko/20100101 Firefox/28.0")
             if cc != LibCURL.CURLE_OK
               error ("CURLOPT_USERAGENT failed: " * LibCURL.bytestring(curl_easy_strerror(cc)))
             end
       end
customize_curl (generic function with 1 method)

julia>

julia> r = get(url,RequestOptions(
       request_timeout=8.0,
       callback=customize_curl))
ERROR: "Error executing request : Problem with the SSL CA cert (path? access rights?)"
 in exec_as_multi at C:\Users\SAMSUNG2\.julia\v0.4\HTTPClient\src\HTTPC.jl:702
 in get at C:\Users\SAMSUNG2\.julia\v0.4\HTTPClient\src\HTTPC.jl:371

julia>

**Comment by porterjamesj** [comment]
This is an `HTTPClient` issue, not a Gumbo one. Gumbo doesn't talk to the network at all, it only deals with parsing HTML once you've gathered it from wherever you want. I personally recommend https://github.com/JuliaWeb/Requests.jl for HTTP in Julia, I've used it successfully in the past.
