### ISSUE TITLE
URL dead (again)?

### ISSUE THREAD

**Issue by ruliana** [porterjamesj/Gumbo.jl#17]
I got the following error message when executing:

``` julia
Pkg.add("Gumbo")
```

Here the error:

```
INFO: Installing Gumbo v0.1.0
INFO: Building Gumbo

WARNING: deprecated syntax "[a=>b, ...]" at /home/ronie/.julia/v0.4/Gumbo/deps/build.jl:19.
Use "Dict(a=>b, ...)" instead.
INFO: Attempting to Create directory /home/ronie/.julia/v0.4/Gumbo/deps/downloads
INFO: Downloading file http://jamesporter.me/static/julia/gumbo-1.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
================================[ ERROR: Gumbo ]================================

LoadError: failed process: Process(`curl -f -o /home/ronie/.julia/v0.4/Gumbo/deps/downloads/gumbo-1.0.tar.gz -L http://jamesporter.me/static/julia/gumbo-1.0.tar.gz`, ProcessExited(22)) [22]
while loading /home/ronie/.julia/v0.4/Gumbo/deps/build.jl, in expression starting on line 19

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Gumbo had build errors.

 - packages with build errors remain installed in /home/ronie/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Gumbo")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
```

Is the URL really dead or am I doing something wrong? =\

**Comment by ruliana** [comment]
I verified the following file:

/home/ronie/.julia/v0.4/Gumbo/deps/build.jl

And find the this at line 7:

```julia
provides(Sources,
         URI("http://jamesporter.me/**static**/julia/gumbo-1.0.tar.gz"),
         libgumbo,
         unpacked_dir="gumbo-1.0")
```

Then I removed the **static** in the path and Pkg.build("Gumbo"). Now it works ^_^

Before trying that, I removed the pkg twice (Pkg.rm("Gumbo")) a I tried twice to install it with no success.

**Comment by jiahao** [comment]
Would it be easier to simply clone from https://github.com/google/gumbo-parser rather than maintain your own?

**Comment by porterjamesj** [comment]
@ruliana sorry for the hassle. [current master has the correct url](https://github.com/porterjamesj/Gumbo.jl/blob/ae072eeb6a7fe31950470dbf4a24e9a69d30e7b7/deps/build.jl#L8), so I suspect this is some sort of caching issue?

@jiahao the problem is that https://github.com/google/gumbo-parser requires running `./autogen.sh` to build, which BinDeps doesn't do. I opened [an issue about it](https://github.com/JuliaLang/BinDeps.jl/issues/82) that never went anywhere. Probably the right thing to do is for google to host a `make dist` tarball, but I never got around to poking them about it.

**Comment by jiahao** [comment]
@porterjamesj if master has the correct URL, then I think all you need to is tag a new version and submit a PR to METADATA.jl

**Comment by ruliana** [comment]
Also, Gumbo.jl 0.1.2 is tagged ``julia 0.4-`` in REQUIRE file, I guess that could be removed as 0.1.2 is pretty compatible to julia 0.4 (as far as I could test).

Want me to make a PR with that? ^_^

**Comment by jiahao** [comment]
> Also, Gumbo.jl 0.1.2 is tagged julia 0.4- in REQUIRE file, I guess that could be removed as 0.1.2 is pretty compatible to julia 0.4 (as far as I could test).

@ruliana I'm not sure what you think that line means, but it means "Julia 0.4 prereleases or higher". Do you mean `julia 0.3` because it is 0.3 compatible?

**Comment by ruliana** [comment]
Maybe I didn't undestand the [doc](http://julia.readthedocs.org/en/latest/manual/packages/#require-speaks-for-itself) :(

The line in [REQUIRE file](https://github.com/porterjamesj/Gumbo.jl/blob/v0.1.2/REQUIRE) is:
```
julia 0.3 0.4-
```

If I got that right, it means: "version 0.3 up to 0.4 pre-release, *not* included". Is that correct? =/

**Comment by jiahao** [comment]
Yes, but I've already changed the [version requirements on master](https://github.com/porterjamesj/Gumbo.jl/blob/ae072eeb6a7fe31950470dbf4a24e9a69d30e7b7/REQUIRE#L1) in the same PR to update the syntax to 0.4 compatibility. If @porterjamesj tags the current commit then the next release should be correctly tagged.

**Comment by ruliana** [comment]
Ahhh! Got it ^_^

Sorry for the confusion. m(_ _)m
