### ISSUE TITLE
Build Error (MethodError: No matching keys)

### ISSUE THREAD

**Issue by Yawolf** [porterjamesj/Gumbo.jl#20]
Hi! I'm using Julia 0.5.0 because a bug in the Package Manager on 0.4.6 version. When I run `Pkg.add("Gumbo")`, the building process ends with this errror:

```
LoadError: MethodError: no method matching keys(::Array{Pair{Symbol,Symbol},1})
Closest candidates are:
  keys(::Associative{K,V})
while loading /home/yagox/.julia/v0.5/Gumbo/deps/build.jl, in expression starting on line 19
```

Thank you! :D

**Comment by porterjamesj** [comment]
It looks like the dictionary declaration syntax [here](https://github.com/porterjamesj/Gumbo.jl/blob/4259cc8b5e9117c94cd9ffc4f40923132e6630d2/deps/build.jl#L19) is no longer valid on 0.5? Not sure. I make no attempt to support development versions of Julia with this package until they're actually released, it's just too much effort to keep up with all the changes. I would happily accept PRs to fix anything you run into though!

**Comment by Yawolf** [comment]
Looks like the error is what you said, a change in the syntax. I will try to fix it when I have a little more free time :D

**Comment by porterjamesj** [comment]
Thank you! And sorry it doesn't work already :/ I think an 0.5 release candidate is in principle going to happen soon, when it does I'll do through and fix everything that broke.

**Comment by porterjamesj** [comment]
Should be fixed by https://github.com/porterjamesj/Gumbo.jl/pull/22
