### ISSUE TITLE
Fails to build with 0.5

### ISSUE THREAD

**Issue by aviks** [porterjamesj/Gumbo.jl#23]
```
================================[ ERROR: Gumbo ]================================
LoadError: MethodError: no method matching keys(::Array{Pair{Symbol,Symbol},1})
Closest candidates are:
  keys(::Associative{K,V}) at dict.jl:118
while loading /home/travis/.julia/v0.5/Gumbo/deps/build.jl, in expression starting on line 19
================================================================================
```

**Comment by aviks** [comment]
This is probably due to a the Dict syntax which was deprecated in 0.4, and hence removed in 0.5. Trying to build Gumbo in 0.4 shows

```
WARNING: deprecated syntax "[a=>b, ...]" at /home/travis/.julia/v0.4/Gumbo/deps/build.jl:19.
Use "Dict(a=>b, ...)" instead.
```

**Comment by aviks** [comment]
Actually this seems fixed in #22 . Could you possibly tag a new version please, so that downstream dependencies can use this?

**Comment by porterjamesj** [comment]
@aviks sure!

**Comment by porterjamesj** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/5779

**Comment by aviks** [comment]
Thanks! FYI https://github.com/Algocircle/Cascadia.jl is now a dependency of Gumbo.jl

**Comment by porterjamesj** [comment]
@aviks cool! glad someone's using it :) let me know if you have any feature requests, i have some bandwidth to work on this right now.
