### ISSUE TITLE
Gumbo install on 0.6 

### ISSUE THREAD

**Issue by sononix** [porterjamesj/Gumbo.jl#41]
Running into an issue of installing gumbo and a docker debian installation - relatively clean install 

was trying to install Genie which a Gumbo dependency....

ProcessExited(77)) [77]
while loading /root/.julia/v0.6/Gumbo/deps/build.jl, in expression starting on line 19

are there any environmental variable that need to be set prior to use 

tks 
M

**Comment by porterjamesj** [comment]
@sononix there shouldn't be! I'll definitely need more information than this to figure out what's wrong . . . can you paste a more complete log of what happens? (i.e. everything from when you typed `Pkg.install` to where that `PrcoessExited` error happens?

**Comment by porterjamesj** [comment]
@sononix I'm going to close this since I don't have enough information to usefully debug, feel free to reopen if you can provide more info.
