### ISSUE TITLE
somethink wrong in Julia 4.0 with Gumbo

### ISSUE THREAD

**Issue by paulanalyst** [porterjamesj/Gumbo.jl#9]
somethink wrong in Julia 4.0 with Gumbo  , at 3.6 ids ok on my machine.     
(file  example.html is in needed dir)
  _       _ _(_)_     |  A fresh approach to technical computing
 (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
  _ _   _| |_  __ _   |  Type "help()" for help.
 | | | | | | |/ _` |  |
 | | |_| | | | (_| |  |  Version 0.4.0-dev+3600 (2015-02-25 15:26 UTC)
_/ |\__'_|_|_|\__'_|  |  Commit f96c23c* (5 days old master)
__/                   |  x86_64-w64-mingw32

ulia> using Base.Test

ulia> using Gumbo

ulia> let
      doc = open("example.html") do example
      example |> readall |> parsehtml
      end
       io = IOBuffer()
      print(io, doc)
      seek(io, 0)
      newdoc = io |> readall |> parsehtml
      @test newdoc == doc
      end

 in print_to_string at string.jl:23
 in print at C:\Users\SAMSUNG2\.julia\v0.4\Gumbo\src\io.jl:88
 in print_to_string at string.jl:23
 in print at C:\Users\SAMSUNG2\.julia\v0.4\Gumbo\src\io.jl:88
 in print_to_string at string.jl:23
 in print at C:\Users\SAMSUNG2\.julia\v0.4\Gumbo\src\io.jl:88
 in print_to_string at string.jl:23
 in print at C:\Users\SAMSUNG2\.julia\v0.4\Gumbo\src\io.jl:88
 in print_to_string at string.jl:23
 in print at C:\Users\SAMSUNG2\.julia\v0.4\Gumbo\src\io.jl:88
 in print_to_string at string.jl:23
 in print at C:\Users\SAMSUNG2\.julia\v0.4\Gumbo\src\io.jl:88
 in print_to_string at string.jl:23
 in print at C:\Users\SAMSUNG2\.julia\v0.4\Gumbo\src\io.jl:88
 in print_to_string at string.jl:23
 in print at C:\Users\SAMSUNG2\.julia\v0.4\Gumbo\src\io.jl:88
 in anonymous at no file:6

....................... while...

**Comment by porterjamesj** [comment]
I explicitly don't support Julia 0.4 since it's been changing so fast and I don't have the time or energy right now to keep up with it. I'm planning on updating to support it once release candidates start coming out. Sorry! :/

**Comment by porterjamesj** [comment]
I'm more than happy to accept pull requests for changes to improve 0.4 compatibility though.
